In [427]:
import pandas as  pd
import numpy as np 
import re

In [428]:
df= pd.read_csv('E:\python\whatmobile\whatmobile\spiders\MobileData.csv')
df.head()

,Name,OS,Weight,SIM,4G Band,CPU,Chipset,GPU,Display Technology,Display Size,Display Resolution,Display Extra Features,Memory Built-in,Card,Camera Main,Camera Features,Camera Front,WLAN,GPS,Data,Sensors,Extra Features,Battery Capacity,Price,Rating
0,itel it9210,NaN,NaN,Dual Sim (Mini-SIM),LTE,NaN,NaN,NaN,QVGA Display,2.4 Inches,NaN,NaN,"124MB Built-in, 64MB RAM","microSD Card, (supports upto 16GB)",1.3 MP,No,No Camera,No,Yes,NaN,NaN,"Internet Explorer, Facebook, Auto call recorde...",Li-ion 1900 mAh,"5,699",5 stars
1,itel Super Guru 600,Nucleus OS,NaN,Dual Sim (Mini-SIM),NaN,312 Mhz,SC6531C Chipset,NaN,LCD Display,2.8 Inches,NaN,NaN,32MB Built-in,"microSD Card, (supports up to 32GB)",1.3 MP Camera,No,No Camera,No,Yes,NaN,NaN,"Metal Plating, Wear Resistant Keypad, UPI Paym...",Li-ion 1900 mAh,"4,499",5 stars
2,Nokia 6310 2021,NaN,NaN,"Dual Sim, Dual Standby (Mini-SIM)","LTE band 1(2100), 3(1800), 5(850), 7(2600), 8(...",NaN,Unisoc 6531F,NaN,QVGA Display,2.8 Inches,240 x 320 Pixels (~143 PPI),NaN,"8MB Built-in, 16MB RAM","microSD Card, (supports upto 32GB)","0.3 MP, LED Flash",Video (320p@15fps),No Camera,No,No,NaN,NaN,"SNS applications, Platic body, Organizer, Voic...","(Li-ion Removable), 1150 mAh","7,800",3 stars
3,itel Power700 Core,NaN,NaN,Dual Sim (Mini-SIM),NaN,NaN,SC6531C,NaN,LCD Display,2.8 Inches,NaN,NaN,NaN,"microSD Card, (supports upto 32GB)","VGA, LED Flash",No,No Camera,No,Yes,NaN,NaN,"Super Bright LED Torch, Internet Explorer, Fac...","Li-ion 2500 mAh, (super battery mode)","3,599",4 stars
4,itel A17,Android 10.0 (Go edition),NaN,"Dual Sim, Dual Standby (Nano-SIM)",LTE,1.3Ghz Quad Core,Spreadtrum SC7731 SoC,ARM Mali-400,"FWVGA Capacitive Touchscreen, Multouch",5.0 Inches,720 x 1520 Pixels (~336 PPI),NaN,"32GB Built-in, 1GB RAM","microSD Card, (supports upto 128GB)","5 MP, LED Flash","Geo-tagging, Phase detection, Video","2 MP, LED Flash","Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot",Yes + A-GPS support,NaN,"Accelerometer, Face ID, Fingerprint (rear moun...","Photo/video editor, Document viewer, Google Se...","(Li-ion Non removable), 2400 mAh","9,999",5 stars

In [429]:
df.columns

Index(['Name', 'OS', 'Weight', 'SIM', '4G Band', 'CPU', 'Chipset', 'GPU',
       'Display Technology', 'Display Size', 'Display Resolution',
       'Display Extra Features', 'Memory Built-in', 'Card', 'Camera Main',
       'Camera Features', 'Camera Front', 'WLAN', 'GPS', 'Data', 'Sensors',
       'Extra Features', 'Battery Capacity', 'Price', 'Rating'],
      dtype='object')

In [430]:
df = df.drop(['Weight','SIM','Display Resolution','4G Band','Data','Card',
              'Chipset','WLAN','GPS','Sensors','Extra Features','Rating'],axis = 1)

In [431]:
df = df[(df['Price'] != 'Coming soon') & (df['Price'] != 'Coming Soon')]
df = df.dropna(axis=0, subset=['Price'])
df = df.dropna(axis=0, subset=['CPU'])
df = df[df['CPU'] != ',']

In [432]:
df.nunique().sort_values(ascending=False)

Name                      655
Camera Main               432
Camera Front              303
Camera Features           294
Price                     238
CPU                       186
Display Extra Features    178
Battery Capacity          137
Memory Built-in           134
GPU                       108
Display Technology         86
Display Size               72
OS                         58
dtype: int64

In [433]:
df.dtypes

Name                      object
OS                        object
CPU                       object
GPU                       object
Display Technology        object
Display Size              object
Display Extra Features    object
Memory Built-in           object
Camera Main               object
Camera Features           object
Camera Front              object
Battery Capacity          object
Price                     object
dtype: object

In [434]:
df.columns

Index(['Name', 'OS', 'CPU', 'GPU', 'Display Technology', 'Display Size',
       'Display Extra Features', 'Memory Built-in', 'Camera Main',
       'Camera Features', 'Camera Front', 'Battery Capacity', 'Price'],
      dtype='object')

In [435]:
df['brand'] = df['Name'].str.split().str[0]

In [436]:
df.isnull().sum().sort_values(ascending=False)

Display Extra Features    303
GPU                        87
Battery Capacity           11
Memory Built-in             6
Display Size                2
Name                        0
OS                          0
CPU                         0
Display Technology          0
Camera Main                 0
Camera Features             0
Camera Front                0
Price                       0
brand                       0
dtype: int64

In [437]:
# Remove commas from 'Price' column and convert to numeric
df['Price'] = df['Price'].str.replace(',', '').astype(int)
df['Price'].dtype

dtype('int32')

In [438]:
df['OS'] = df['OS'].astype(str)

# Extract Android version number
def extract_android_version(os):
    try:
        android_version = re.findall(r'Android\s+([Vv]?\d+(\.\d+)?)', os)
        if android_version:
            return android_version[0][0]
        else:
            raise Exception
    except:
        # Try another pattern for Android versions
        android_version = re.findall(r'Android\s+OS,\s+v(\d+(\.\d+)?)', os)
        if android_version:
            return android_version[0][0]
        else:
            # Try pattern for iOS versions
            ios_version = re.findall(r'(IOS?\s+(\d+(\.\d+)?)|(\d+(\.\d+)?))', os)
            if ios_version:
                for match in ios_version:
                    if match[1]:
                        return match[1]
                return ios_version[0][3]  # Fallback to the last matched group if specific version not found
            else:
                return np.nan

# Extract OS type
def extract_os_type(os):
    os_type = re.findall(r'(Android|IOS)\s+(\d+(\.\d+)?)?', os)
    if os_type:
        return os_type[0][0]
    else:
        # Try another pattern for OS type
        os_type = re.findall(r'(Android|IOS)', os)
        if os_type:
            return os_type[0]
        else:
            # Try a simpler pattern for OS type
            if 'Android' in os:
                return 'Android'
            elif 'IOS' in os:
                return 'IOS'
            else:
                return np.nan

def fill_android_version(row):
    if 'Apple' in row['Name']:
        row['OS_Type'] = 'IOS'
    else:
        row['OS_Type'] = 'Android'
    return row

            
# Apply functions to extract Android version and OS type
df['OS_Version'] = df['OS'].apply(extract_android_version)
df['OS_Type'] = df['OS'].apply(extract_os_type)
df['OS_Version'] = df['OS_Version'].str.replace('^[vV]', '', regex=True)
df = df.apply(fill_android_version, axis=1)

In [439]:
df[['OS','OS_Version','OS_Type']].head(10)

                               OS OS_Version  OS_Type
1                      Nucleus OS        NaN  Android
4       Android 10.0 (Go edition)       10.0  Android
9   Android V8.1 Oreo; Go Edition        8.1  Android
10                  Android 13 OS         13  Android
12                  Android 13 OS         13  Android
13                  Android 12 OS         12  Android
15                         IOS 11         11      IOS
17                  Android 11 OS         11  Android
18                  Android 13 OS         13  Android
26                  Android 11 OS         11  Android

In [440]:
df['OS_Version']=df['OS_Version'].astype(float)
df['OS_Version']=df['OS_Version'].fillna(df['OS_Version'].mean())
df['OS_Type'].replace({'Android': 1, 'IOS': 2}, inplace=True)
df['OS_Type']=df['OS_Type'].astype(int)

In [441]:
# 1. Extracting Core Count
core_patterns = r'(octa|hexa|quad|dual|single)'
df['Core'] = df['CPU'].str.extract(core_patterns, flags=re.IGNORECASE, expand=False).str.lower()
# Mapping extracted core strings to numerical values
core_mapping = {'dual': 2, 'quad': 4, 'hexa': 6, 'octa': 8,'single': 1}
# Convert extracted core strings to numerical values
df['Core'] = df['Core'].str.lower().map(core_mapping)

In [442]:
print(df.iloc[:, -3:].head(20))

    OS_Version  OS_Type  Core
1     10.59584        1   NaN
4     10.00000        1   4.0
9      8.10000        1   4.0
10    13.00000        1   8.0
12    13.00000        1   8.0
13    12.00000        1   8.0
15    11.00000        2   6.0
17    11.00000        1   8.0
18    13.00000        1   8.0
26    11.00000        1   8.0
36     6.00000        1   8.0
42     7.00000        1   8.0
43     6.00000        1   8.0
44     7.10000        1   4.0
46     7.00000        1   4.0
48     8.10000        1   8.0
49     9.00000        1   8.0
50     7.00000        1   8.0
51    10.59584        1   1.0
52     9.00000        1   2.0

In [443]:
df.isnull().sum().sort_values(ascending=False)

Display Extra Features    303
GPU                        87
Battery Capacity           11
Memory Built-in             6
Core                        5
Display Size                2
OS_Type                     0
OS_Version                  0
brand                       0
Price                       0
Name                        0
Camera Front                0
Camera Features             0
OS                          0
Display Technology          0
CPU                         0
Camera Main                 0
dtype: int64

In [444]:
def map_gpu_value(gpu):
    if pd.isna(gpu):
        return 0
    elif 'apple' in gpu.lower():
        return 5
    elif 'adreno' in gpu.lower():
        return 4
    elif 'mali' in gpu.lower():
        return 3
    elif 'powervr' in gpu.lower():
        return 2
    else:
        return 1

# Apply function to map GPU values
df['GPU'] = df['GPU'].apply(map_gpu_value)

In [445]:
def create_new_columns(row):
    # Convert row value to lowercase for case-insensitive comparison
    row_lower = row.lower()
    
    # Initialize column values as 0
    amoled = 0
    lcd = 0
    hd = 0
    colors_16m = 0
    colors_1b = 0
    multitouch = 0
    
    # Check if column name is found in the value
    if 'amoled' in row_lower:
        amoled = 1
    if 'lcd' in row_lower:
        lcd = 1
    if 'hd' in row_lower:
        hd = 1
    if '16m colors' in row_lower:
        colors_16m = 1
    if '1b colors' in row_lower:
        colors_1b = 1
    if 'multitouch' in row_lower:
        multitouch = 1
    
    return pd.Series([amoled, lcd, hd, colors_16m, colors_1b, multitouch])

# Create new columns
df[['Amoled', 'LCD', 'HD', '16M', '1B', 'Multitouch']] = df['Display Technology'].apply(create_new_columns)

In [446]:
# Remove "inches" from the values
df['Display Size'] = df['Display Size'].str.replace(' Inches', '',flags=re.IGNORECASE, regex=False)

# Convert the column to numeric data type
df['Display Size'] = pd.to_numeric(df['Display Size'], errors='coerce')

In [447]:
df.isnull().sum().sort_values(ascending=False)

Display Extra Features    303
Battery Capacity           11
Memory Built-in             6
Core                        5
Display Size                2
brand                       0
1B                          0
16M                         0
HD                          0
LCD                         0
Amoled                      0
OS_Type                     0
OS_Version                  0
Name                        0
Price                       0
OS                          0
Camera Front                0
Camera Features             0
Camera Main                 0
Display Technology          0
GPU                         0
CPU                         0
Multitouch                  0
dtype: int64

In [448]:
df['Display Extra Features'] = df['Display Extra Features'].notna().astype(int)

In [449]:
# Extract Built-in Memory and RAM using regex
df['Memory'] = df['Memory Built-in'].str.extract(r'(\d+GB|\d+MB)', flags = re.IGNORECASE)
df['RAM'] = df['Memory Built-in'].str.extract(r'(\d+GB|\d+MB) RAM', flags = re.IGNORECASE)

In [450]:
df = df.drop(['Memory Built-in'],axis = 1)
df = df.dropna(axis=0, subset=['Memory'])

In [451]:
df['RAM'].fillna('0', inplace=True)

In [452]:
# Multiply the numbers with 1000 where 'GB' is present
df['Memory'] = df['Memory'].apply(lambda x: int(x.replace('GB', '')) * 1000 if 'GB' in x else int(x.replace('MB', '')))
df['RAM'] = df['RAM'].apply(lambda x: int(x.replace('GB', '')) * 1000 if 'GB' in x else int(x.replace('MB', '')))

In [453]:
print(df['Memory'].unique())
print( df['RAM'].unique())

[    32  32000  16000 256000 128000  64000   4000   8000 512000   3000]
[    0  1000  8000  4000  6000  3000  2000   768 12000   512]

In [454]:
# Extract main camera megapixels
df['Camera mp'] = df['Camera Main'].apply(lambda x: float(re.search(r'(\d+(\.\d+)?) MP', x).group(1)) if re.search(r'(\d+(\.\d+)?) MP', x) else None)
# Extract features for dual, triple, and quad cameras
df['Dual camera'] = df['Camera Main'].str.contains('Dual', case=False).astype(int)
df['Triple camera'] = df['Camera Main'].str.contains('Triple', case=False).astype(int)
df['Quad camera'] = df['Camera Main'].str.contains('Quad', case=False).astype(int)

In [455]:
df['Front Camera mp'] = df['Camera Front'].apply(lambda x: float(re.search(r'(\d+(\.\d+)?) MP', x).group(1)) if re.search(r'(\d+(\.\d+)?) MP', x) else None)

In [456]:
df['Front Camera mp'].fillna(0,inplace = True)

In [457]:

# Extract battery capacity in mAh and battery type
df['Battery Capacity (mAh)'] = df['Battery Capacity'].str.extract(r'(\d+) mAh').astype(float)
df['Battery Type'] = df['Battery Capacity'].str.extract(r'(Li-ion|Li-Po)', flags=re.IGNORECASE)
df['Battery Type'] = df['Battery Type'].map({'Li-ion': 1, 'Li-Po': 2}).fillna(0).astype(int)

# Display the DataFrame with the new columns
print(df[['Battery Type', 'Battery Capacity']].head())

    Battery Type                  Battery Capacity
1              1                   Li-ion 1900 mAh
4              1  (Li-ion Non removable), 2400 mAh
9              1  (Li-ion Non removable), 2200 mAh
10             2   (Li-Po Non removable), 5000 mAh
12             1  (Li-ion Non removable), 5000 mAh

In [458]:
df['Battery Type'].unique()

array([1, 2, 0])

In [459]:
null_battery_capacity_rows = df[df['Battery Capacity (mAh)'].isnull()]
print(null_battery_capacity_rows[['Battery Capacity','Battery Capacity (mAh)', 'Battery Type']])

           Battery Capacity  Battery Capacity (mAh)  Battery Type
202  (Li-ion Non removable)                     NaN             1
213    Li-ion Non removable                     NaN             1
215    Li-ion Non removable                     NaN             1
498    Li-ion Non removable                     NaN             1
887    Long Lasting Battery                     NaN             0
901    Long Lasting battery                     NaN             0
920               Removable                     NaN             0
935        Li-ion Removable                     NaN             1
936    Li-ion Non removable                     NaN             1
952          Li-ion battery                     NaN             1
966        Li-ion Removable                     NaN             1

In [460]:
df.dropna(subset=['Battery Capacity (mAh)'], inplace=True)

In [461]:
df = df.drop(['Name','Battery Capacity','OS','CPU','Display Technology','Camera Main','Camera Features',
             'Camera Front'],axis = 1)

In [462]:
df.dropna(inplace=True)

In [463]:
df.dtypes

GPU                         int64
Display Size              float64
Display Extra Features      int32
Price                       int64
brand                      object
OS_Version                float64
OS_Type                     int32
Core                      float64
Amoled                      int64
LCD                         int64
HD                          int64
16M                         int64
1B                          int64
Multitouch                  int64
Memory                      int64
RAM                         int64
Camera mp                 float64
Dual camera                 int32
Triple camera               int32
Quad camera                 int32
Front Camera mp           float64
Battery Capacity (mAh)    float64
Battery Type                int32
dtype: object

In [464]:
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder

# Splitting data into train and test sets
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize TargetEncoder
encoder = TargetEncoder(cols=['brand'])

# Fit the encoder on the training data and transform both training and test data
X_train_encoded = encoder.fit_transform(X_train, y_train)
X_test_encoded = encoder.transform(X_test)

# Concatenate X_train_encoded and X_test_encoded with their corresponding y values
df_train_encoded = pd.concat([X_train_encoded, y_train], axis=1)
df_test_encoded = pd.concat([X_test_encoded, y_test], axis=1)

In [465]:
df_train_encoded

,GPU,Display Size,Display Extra Features,brand,OS_Version,OS_Type,Core,Amoled,LCD,HD,16M,1B,Multitouch,Memory,RAM,Camera mp,Dual camera,Triple camera,Quad camera,Front Camera mp,Battery Capacity (mAh),Battery Type,Price
276,4,6.550,1,68064.251292,10.0,1,8.0,1,0,0,0,0,0,256000,12000,48.0,1,1,0,16.0,4300.0,2,109999
384,4,6.780,1,55537.081118,14.0,1,8.0,1,0,0,0,0,1,256000,12000,50.0,0,1,0,50.0,5000.0,2,139999
640,2,6.500,1,65650.150413,12.0,1,4.0,0,1,0,1,0,1,32000,3000,8.0,1,0,0,5.0,5000.0,1,32999
641,2,6.520,0,47011.961916,12.0,1,8.0,0,1,0,1,0,1,64000,4000,50.0,0,1,0,8.0,5000.0,2,34999
526,4,6.350,0,55537.081118,9.0,1,8.0,0,1,0,1,0,1,32000,2000,13.0,1,0,0,8.0,5000.0,2,17999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,3,6.600,1,50092.160951,11.0,1,8.0,0,1,0,1,0,1,64000,4000,48.0,0,1,1,8.0,5000.0,2,22699
145,1,6.517,0,39646.949433,12.0,1,4.0,0,1,0,1,0,1,32000,2000,13.0,0,1,0,5.0,5000.0,2,21499
337,3,6.700,1,35648.134598,12.0,1,8.0,1,0,0,0,0,1,128000,6000,50.0,0,1,0,16.0,5000.0,2,50999
573,2,6.600,0,35648.134598,10.0,1,4.0,0,1,0,1,0,1,64000,3000,13.0,0,1,0,8.0,5000.0,2,18499
141,3,5.500,0,32010.991498,11.0,1,4.0,0,0,0,0,0,1,8000,1000,5.0,0,0,0,2.0,4000.0,1,23999

<h2 align="center">Model Training</h2>

In [468]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import pandas as pd

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

# Initialize Random Forest Regressor
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train_scaled, y_train)
# Get feature importances
feature_importances = rf.feature_importances_
# Create DataFrame to display feature importances
feature_importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importances})
# Sort the DataFrame by importance
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

print(feature_importance_df)

                   Feature  Importance
13                  Memory    0.534535
14                     RAM    0.076950
15               Camera mp    0.075030
3                    brand    0.063039
1             Display Size    0.057555
20  Battery Capacity (mAh)    0.035022
7                   Amoled    0.033996
0                      GPU    0.024878
4               OS_Version    0.020552
19         Front Camera mp    0.018320
8                      LCD    0.014906
10                     16M    0.013177
16             Dual camera    0.012056
2   Display Extra Features    0.003539
18             Quad camera    0.003203
12              Multitouch    0.003167
17           Triple camera    0.002752
5                  OS_Type    0.002476
11                      1B    0.002465
21            Battery Type    0.001994
6                     Core    0.000377
9                       HD    0.000013

In [467]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
import numpy as np

# Separate features and target variable for training and testing datasets
X_train = df_train_encoded.drop('Price', axis=1)
y_train = df_train_encoded['Price']
X_test = df_test_encoded.drop('Price', axis=1)
y_test = df_test_encoded['Price']

# Initialize and train three different models
models = {
    "Random Forest": RandomForestRegressor(random_state=42),
    "Linear Regression": LinearRegression(),
    "Support Vector Machine": SVR()
}

# Train models and print metrics for each
print("Models without scaling:")
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} - Root Mean Squared Error: {rmse}, Mean Absolute Error: {mae}, R^2 Score: {r2}")

# Scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train models on scaled data and print metrics for each
print("\nModels with scaling:")
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} - Root Mean Squared Error: {rmse}, Mean Absolute Error: {mae}, R^2 Score: {r2}")

# Feature selection using RFE
rfe = RFE(estimator=RandomForestRegressor(random_state=42), n_features_to_select=15)
rfe.fit(X_train, y_train)
selected_features = X_train.columns[rfe.support_]

# Train models on selected features for both scaled and unscaled data, and print metrics for each
print("\nModels with feature selection:")
for name, model in models.items():
    # Train on unscaled data
    model.fit(X_train[selected_features], y_train)
    y_pred = model.predict(X_test[selected_features])
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} (Unscaled) - Root Mean Squared Error: {rmse}, Mean Absolute Error: {mae}, R^2 Score: {r2}")
    
    # Train on scaled data
    model.fit(X_train_scaled[:, rfe.support_], y_train)
    y_pred = model.predict(X_test_scaled[:, rfe.support_])
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} (Scaled) - Root Mean Squared Error: {rmse}, Mean Absolute Error: {mae}, R^2 Score: {r2}")

Models without scaling:
Random Forest - Root Mean Squared Error: 15508.226204837365, Mean Absolute Error: 10460.974533333336, R^2 Score: 0.8412695236317458
Linear Regression - Root Mean Squared Error: 22430.09426493131, Mean Absolute Error: 14958.986637393988, R^2 Score: 0.6679539922302553
Support Vector Machine - Root Mean Squared Error: 41125.87569697268, Mean Absolute Error: 25568.724480565594, R^2 Score: -0.11626262178662983

Models with scaling:
Random Forest - Root Mean Squared Error: 15488.231980986633, Mean Absolute Error: 10434.218373333335, R^2 Score: 0.8416785513010641
Linear Regression - Root Mean Squared Error: 22430.09426497023, Mean Absolute Error: 14958.986637433003, R^2 Score: 0.6679539922291031
Support Vector Machine - Root Mean Squared Error: 41149.155243904395, Mean Absolute Error: 25581.77324912111, R^2 Score: -0.11752671367240586

Models with feature selection:
Random Forest (Unscaled) - Root Mean Squared Error: 15082.753647995429, Mean Absolute Error: 10289.612399999998, R^2 Score: 0.8498596787580887
Random Forest (Scaled) - Root Mean Squared Error: 15126.076013375008, Mean Absolute Error: 10302.188239999998, R^2 Score: 0.8489959405592352
Linear Regression (Unscaled) - Root Mean Squared Error: 22919.879959651706, Mean Absolute Error: 16128.880149682489, R^2 Score: 0.6532944905868676
Linear Regression (Scaled) - Root Mean Squared Error: 22919.879959681006, Mean Absolute Error: 16128.880149720917, R^2 Score: 0.6532944905859812
Support Vector Machine (Unscaled) - Root Mean Squared Error: 41125.39488997996, Mean Absolute Error: 25568.382167303917, R^2 Score: -0.1162365212488139
Support Vector Machine (Scaled) - Root Mean Squared Error: 41143.985474133595, Mean Absolute Error: 25578.0696849007, R^2 Score: -0.11724593061042432

In [426]:
from sklearn.model_selection import GridSearchCV

# Selected features from RFE
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

# Initialize RandomForestRegressor
rf = RandomForestRegressor(random_state=42)

# Define hyperparameters for GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Perform GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train_selected, y_train)

# Best hyperparameters
best_params = grid_search.best_params_

# Train RandomForestRegressor with best hyperparameters
best_rf = RandomForestRegressor(**best_params, random_state=42)
best_rf.fit(X_train_selected, y_train)

# Evaluate on test data
y_pred = best_rf.predict(X_test_selected)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Best Hyperparameters:", best_params)
print("Root Mean Squared Error:", rmse)
print("Mean Absolute Error:", mae)
print("R^2 Score:", r2)

Best Hyperparameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Root Mean Squared Error: 15260.584516009314
Mean Absolute Error: 10352.1176
R^2 Score: 0.8462983950658004